spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

kafka:
  bootstrap-servers: localhost:9092
  hub-topic: telemetry.hubs.v1
  sensor-topic: telemetry.sensors.v1

logbook:
  format:
    style: http

logging:
  level:
    org:
      zalando:
        logbook: TRACE

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/