server:
  port: 8080
grpc:
  server:
    port: 59091

spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

kafka:
  bootstrap-servers: localhost:9092
  hub-topic: telemetry.hubs.v1
  sensor-topic: telemetry.sensors.v1

logbook:
  format:
    style: http

logging:
  level:
    org:
      zalando:
        logbook: TRACE