spring:
  application:
    name: aggregator
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

kafka:
  bootstrap-servers: localhost:9092
  sensor-topic: telemetry.sensors.v1
  snapshot-topic: telemetry.snapshots.v1
  group-id: aggregator-group
  auto-commit: false

logbook:
  format:
    style: http

logging:
  level:
    org:
      zalando:
        logbook: TRACE