spring:
  application:
    name: aggregator
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/