spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: ''
        native:
          searchLocations:
            - classpath:config/telemetry/
server:
  port: 0

logging:
  level:
    org.springframework.cloud.config.server: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
      non-secure-port: ${server.port}
      instance-id: ${spring.application.name}:${random.value}